### ISSUE TITLE
Current achievable quality

### ISSUE THREAD

**Issue by bdhammel** [daniel-code/TubeViT#16]
Hi Daniel,

Thank you very much for making your implementation available. 

Would you be able to share some of your achieved accuracies? as well as any suspicions as to what might help close the gap with the paper? I know you've listed features to be added elsewhere, just curious if there were specific priorities.

Great work,
Ben

**Comment by farewellthree** [comment]
so what are the achieved accuracies? I'm still curious about this.

**Comment by daniel-code** [comment]
Hi Ben (@bdhammel) and @farewellthree,

Sorry for the delayed reply. 
The model could not train well in the UCF101 dataset. The training accuracy is not greater than 70%.
I am looking for the root cause of this.
The reasons may be:
1. Data augmentation
2. number of tokens is different than the paper.

If you find out the reason, welcome to leave a comment. Thanks!

Sincerely,

Daniel

**Comment by bdhammel** [comment]
Thanks Daniel! I'm seeing the same thing. I topped out around 40% on ucf101, based on similar models I'd expect >95%. For kinetics 700 I was never able to get anything > 0. 

I was pulled into some other tasks the last few weeks, but I should be free to circle back around to this now. I'll update here if I find anything. 

Thanks again for posting the code!

**Comment by babyta** [comment]
Please tell me, what accuracy can the latest code achieve on the ucf101 data set?
